name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-22.04
            ARCH: x86_64
            COMPILER: gcc
            LIB_NAME: libaiken_c_ffi.so
            TARGET_NAME: linux-x86_64-gcc_libaiken_c_ffi.so
          - TARGET: aarch64-unknown-linux-gnu
            OS: ubuntu-22.04
            ARCH: arm64
            COMPILER: gcc
            LIB_NAME: libaiken_c_ffi.so
            TARGET_NAME: linux-arm64-gcc_libaiken_c_ffi.so
          - TARGET: armv7-unknown-linux-gnueabihf
            OS: ubuntu-22.04
            ARCH: armv7
            COMPILER: gcc
            LIB_NAME: libaiken_c_ffi.so
            TARGET_NAME: linux-armv7-gcc_libaiken_c_ffi.so
          - TARGET: arm-unknown-linux-gnueabihf
            OS: ubuntu-22.04
            ARCH: armv6
            COMPILER: gcc
            LIB_NAME: libaiken_c_ffi.so
            TARGET_NAME: linux-armv6-gcc_libaiken_c_ffi.so
          # macOS
          - TARGET: x86_64-apple-darwin
            OS: macos-latest
            ARCH: x86_64
            COMPILER: gcc
            LIB_NAME: libaiken_c_ffi.dylib
            TARGET_NAME: darwin-x86_64-gcc_libaiken_c_ffi.dylib
          - TARGET: aarch64-apple-darwin
            OS: macos-latest
            ARCH: arm64
            COMPILER: gcc
            LIB_NAME: libaiken_c_ffi.dylib
            TARGET_NAME: darwin-arm64-gcc_libaiken_c_ffi.dylib
          # Windows
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest
            ARCH: x86_64
            COMPILER: msvc
            LIB_NAME: aiken_c_ffi.dll
            TARGET_NAME: windows-x86_64-msvc_aiken_c_ffi.dll
          - TARGET: x86_64-pc-windows-gnu
            OS: windows-latest
            ARCH: x86_64
            COMPILER: mingw
            LIB_NAME: aiken_c_ffi.dll
            TARGET_NAME: windows-x86_64-mingw_aiken_c_ffi.dll
#    needs: test
    runs-on: ${{ matrix.OS }}
    env:
      NAME: libaiken_c_ffi
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      LIB_NAME: ${{ matrix.LIB_NAME }}
      TARGET_NAME: ${{ matrix.TARGET_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-${{matrix.TARGET}}
      - name: List
        run: find ./
      - name: Install and configure dependencies
        run: |
          # Ubuntu: install cross-compilation tools
          if [[ $OS =~ ^ubuntu.*$ ]]; then
            sudo apt-get update
            sudo apt-get install -qq crossbuild-essential-arm64 crossbuild-essential-armhf libssl-dev
          fi

          # Windows mingw: add mingw to PATH
          if [[ $OS == "windows-latest" && $TARGET == "x86_64-pc-windows-gnu" ]]; then
            echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
          fi

          # Linux cross-compilation configuration
          cat >>~/.cargo/config <<EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          [target.armv7-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"
          [target.arm-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"
          EOF
      - name: Install rust target
        run: rustup target add $TARGET
      - name: Run build
        run: cargo build --release --verbose --target $TARGET
      - name: List target
        run: find ./target
      - name: Copy artifact
        run: |
          mkdir -p ./artifacts
          
          if [[ $GITHUB_REF_TYPE =~ ^tag$ ]]; then
            TAG=$GITHUB_REF_NAME
          else
            TAG=$GITHUB_SHA
          fi
          mv ./target/$TARGET/release/$LIB_NAME ./artifacts/$TARGET_NAME
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./artifacts/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
